### ISSUE TITLE
Document features available or missing in the README

### ISSUE THREAD

**Issue by neuromancer** [opennox/opennox#473]
It will be useful for new user to know how feature complete is this re-implementation in the README. In particular:

* Is the single/coop player campaign completable?
* Which releases are supported? (e.g. GOG, retail, etc)
* Is multiplayer available and supports multiple platforms (e.g. Linux and Windows players in the same battle)?

additional, which new features are or will be available, including: more screen resolutions, UI scaling, controller support, etc.

**Comment by dennwc** [comment]
Everything that original Nox support must work. We support all official releases (GoG, Origin).

Regarding new features, do you have any particular format in mind? Some features might be mod-related, for example. We have a few user-facing ones documented as well (for example [new Nox Quest controls](https://github.com/noxworld-dev/opennox/blob/dev/docs/game-quest.md)), but we should definitely update those.

Feel free to PR a change if you have some specific proposal. Otherwise we will start documenting features we have (update `docs` folder), and maybe eventually will create a static website version via Github Pages.
