### ISSUE TITLE
Singleplayer SIGSEGV during play after certain commit

### ISSUE THREAD

**Issue by blmarket** [opennox/opennox#524]
Test scenario:
Start single player game, choose warrior class, get into the castle, talk to the gauntlet guard, talk to another NPC and choose Yes, follow the NPC and get into the building, trigger the switch in there:

Expected result: Whole city power gets off, NPC says something
Actual result in dev: Game breaks with SIGSEGV

I was able to bisect which commit caused the break, and it was... https://github.com/noxworld-dev/opennox/commit/200ede23c7bc6d88d643a4cc86677fe0f150f881
I saw the commit replaced whole noxscript to use Go engine, so I think something went wrong during porting.

Build environment: Linux, used both Go 1.18 and 1.19 and both failed same.

I want to work on the fix as well, but need some help to setup dev environment. Any suggested IDE to use? (I tried vscode but currently struggling to make it understand GOARCH=386 etc etc... any help will be great)

**Comment by dennwc** [comment]
Thank you for bisecting, it really helps! Since you already know the exact moment when it happens, it would be great to attach a save file just before the action that causes the crash (before power goes off?).

Regarding dev environment, I would suggest to ignore native build command provided by IDE and use our build script. Passing all the build options is a pain. I personally use Goland (from Jetbrains), but still use the script to build it.

**Comment by blmarket** [comment]
Re: save file - https://blmarket.net/NOX-SAVE0002.tar.gz (I don't know how to upload binary file to GitHub. shame...)
Re: IDE and how to fix - Thanks for suggestion. Seems it supports Go better than VSCode at least for CGO syntax. Let me keep working on this, or I'll update here if I can't fix it in a week.
