### ISSUE TITLE
Dialog does not play even though present in game data

### ISSUE THREAD

**Issue by al0fdf** [opennox/opennox#602]
Running commit b6bbbbf11

I've started a new game as a conjurer, but cannot hear any voice lines from NPC's. That is the 'Greetings citizens of IX...'. I can still hear game sounds and the 'argh!' of the necromancer when being hit.

**Comment by dennwc** [comment]
@al0fdf maybe a naive question, but can you try to enable/disable the dialog sound in options and/or changing its volume? I just tested this on `dev` (8b5353827a3aebddcf0261f854617e611a43409e) and everything appears to work fine :thinking:

**Comment by KILAH4716** [comment]
I want to ask to clarify: Can you hear "Get away from me, filthy peasants!" Because the "Argh!" dialogue is an actual spoken line of dialogue, not just the Necromancer getting hit.

Entities being vocal in battle, such as getting hurt are sound effects, but speech in dialogue boxes and speech bubbles are dialogue. If you can hear "Get away from me..." but NOT "Greetings, citizens...", then this is a deeper problem. But if you can hear both, then look at your dialogue volume.

https://www.youtube.com/watch?v=9SVriKb8YL8

If you listen carefully at 1:36, you can listen to the spoken dialogue after the getting hurt sound effect.

**Comment by al0fdf** [comment]
My bad. The dialogue volume was turned all the way down.
